### ISSUE TITLE
Compatibility Question

### ISSUE THREAD

**Issue by BeansBeefBroccoli** [TeamMidnightDust/BetterBeds#5]
Is this mod compatible with Sodium, Indium, and EBE on 1.18.1?

**Comment by PweSol** [comment]
Yes

**Comment by BeansBeefBroccoli** [comment]
Cool, thanks!

**Comment by yesn0t** [comment]
> Yes

Compatible means :
* it will not cause errors with EBE (and not do anything), 
* or it will replace EBE's beds ?

the description says "_Mods that add beds using a custom block entity renderer are untouched_."
However EBE claims : "_Makes some block entities use baked block models rather than laggy entity models_."
i.e is there a benefit for using this mod alongside EBE ? or do they do the same thing ?
thanks

perhaps a comparison table would be helpful 

| mod | renderer | models |
| ------ | ----------- | --------- |
| vanilla | vanilla entity renderer | vanilla entity models |
| EBE    | ??? vanilla block renderer ? | custom block models | 
| BetterBeds | vanilla block renderer | custom block models |

@PweSol  so my question is , i don't know how this mod will interact (or not) with EBE because i don't know which renderer is used by EBE for the beds :/
is the table above even correct ? i'd appreciate any insight

for convenience : 
* EBE description https://modrinth.com/mod/ebe
* BetterBeds description (is more complete than README) https://modrinth.com/mod/better-beds

**Comment by Motschen** [comment]
EBE and BetterBeds basically do the same thing to beds, though BetterBeds will come with fancy resourcepacks.
